# Generated by Django 3.2 on 2023-08-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
        ('users', '0005_auto_20230816_1738'),
    ]

    operations = [
    ]
